version: 0.2

phases:
  install:
    commands:
      - echo installing NGINX
      - sudo apt-get update -y
      - apt-get install -y nginx
  build:
    commands:
      - echo Build started on date
      - cp "**/*" var/www/html
  post_build:
    commands:
      - echo Configuring NGINX
  artifacts:
    files:
      - "**/*"
